/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IWegaRandomizer__factory } from "./IWegaRandomizer__factory";
export { WegaRandomizer__factory } from "./WegaRandomizer__factory";
