/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumber, BytesLike, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IERC20EscrowEventsInterface extends utils.Interface {
  functions: {};

  events: {
    "WagerRequestCreation(bytes32,address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "WagerRequestCreation"): EventFragment;
}

export interface WagerRequestCreationEventObject {
  escrowId: string;
  token: string;
  creator: string;
  wager: BigNumber;
}
export type WagerRequestCreationEvent = TypedEvent<
  [string, string, string, BigNumber],
  WagerRequestCreationEventObject
>;

export type WagerRequestCreationEventFilter =
  TypedEventFilter<WagerRequestCreationEvent>;

export interface IERC20EscrowEvents extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IERC20EscrowEventsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "WagerRequestCreation(bytes32,address,address,uint256)"(
      escrowId?: PromiseOrValue<BytesLike> | null,
      token?: PromiseOrValue<string> | null,
      creator?: PromiseOrValue<string> | null,
      wager?: null
    ): WagerRequestCreationEventFilter;
    WagerRequestCreation(
      escrowId?: PromiseOrValue<BytesLike> | null,
      token?: PromiseOrValue<string> | null,
      creator?: PromiseOrValue<string> | null,
      wager?: null
    ): WagerRequestCreationEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
