/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IGameControllerEventsInterface extends utils.Interface {
  functions: {};

  events: {
    "DeclareWinner(bytes32,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DeclareWinner"): EventFragment;
}

export interface DeclareWinnerEventObject {
  escrowId: string;
  winner: string;
}
export type DeclareWinnerEvent = TypedEvent<
  [string, string],
  DeclareWinnerEventObject
>;

export type DeclareWinnerEventFilter = TypedEventFilter<DeclareWinnerEvent>;

export interface IGameControllerEvents extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IGameControllerEventsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "DeclareWinner(bytes32,address)"(
      escrowId?: PromiseOrValue<BytesLike> | null,
      winner?: null
    ): DeclareWinnerEventFilter;
    DeclareWinner(
      escrowId?: PromiseOrValue<BytesLike> | null,
      winner?: null
    ): DeclareWinnerEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
