/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../common";

export interface IWegaRandomizerControllerEventsInterface extends Interface {
  getEvent(nameOrSignatureOrTopic: "RandomizerSet"): EventFragment;
}

export namespace RandomizerSetEvent {
  export type InputTuple = [newRandomizer: AddressLike];
  export type OutputTuple = [newRandomizer: string];
  export interface OutputObject {
    newRandomizer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IWegaRandomizerControllerEvents extends BaseContract {
  connect(runner?: ContractRunner | null): IWegaRandomizerControllerEvents;
  waitForDeployment(): Promise<this>;

  interface: IWegaRandomizerControllerEventsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "RandomizerSet"
  ): TypedContractEvent<
    RandomizerSetEvent.InputTuple,
    RandomizerSetEvent.OutputTuple,
    RandomizerSetEvent.OutputObject
  >;

  filters: {
    "RandomizerSet(address)": TypedContractEvent<
      RandomizerSetEvent.InputTuple,
      RandomizerSetEvent.OutputTuple,
      RandomizerSetEvent.OutputObject
    >;
    RandomizerSet: TypedContractEvent<
      RandomizerSetEvent.InputTuple,
      RandomizerSetEvent.OutputTuple,
      RandomizerSetEvent.OutputObject
    >;
  };
}
