/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IWegaERC20Escrow } from "./IWegaERC20Escrow";
export type { WegaERC20Escrow } from "./WegaERC20Escrow";
