/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { WegaEscrowManagerRole__factory } from "./WegaEscrowManagerRole__factory";
export { WegaGameManagerRole__factory } from "./WegaGameManagerRole__factory";
