/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { WegaEscrowManagerRole } from "./WegaEscrowManagerRole";
export type { WegaGameManagerRole } from "./WegaGameManagerRole";
