/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IWegaRandomNumberControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addRandomNumbers"
      | "generate"
      | "randomNumbersCount"
      | "seedRandomizer"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addRandomNumbers",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "generate",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "randomNumbersCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seedRandomizer",
    values: [BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "addRandomNumbers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "generate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "randomNumbersCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seedRandomizer",
    data: BytesLike
  ): Result;
}

export interface IWegaRandomNumberController extends BaseContract {
  connect(runner?: ContractRunner | null): IWegaRandomNumberController;
  waitForDeployment(): Promise<this>;

  interface: IWegaRandomNumberControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addRandomNumbers: TypedContractMethod<
    [randomNumbers: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  generate: TypedContractMethod<
    [denominator: BigNumberish, nonce: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  randomNumbersCount: TypedContractMethod<[], [bigint], "view">;

  seedRandomizer: TypedContractMethod<
    [randomNumbers: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addRandomNumbers"
  ): TypedContractMethod<[randomNumbers: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "generate"
  ): TypedContractMethod<
    [denominator: BigNumberish, nonce: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "randomNumbersCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "seedRandomizer"
  ): TypedContractMethod<[randomNumbers: BigNumberish[]], [void], "nonpayable">;

  filters: {};
}
