/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IWegaGameControllerInterface extends utils.Interface {
  functions: {
    "createGameAndDepositInitialWager(address,uint256,uint256,uint8)": FunctionFragment;
    "depositOrPlay(bytes32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "createGameAndDepositInitialWager" | "depositOrPlay"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createGameAndDepositInitialWager",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositOrPlay",
    values: [PromiseOrValue<BytesLike>]
  ): string;

  decodeFunctionResult(
    functionFragment: "createGameAndDepositInitialWager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositOrPlay",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IWegaGameController extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IWegaGameControllerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createGameAndDepositInitialWager(
      tokenAddress: PromiseOrValue<string>,
      requiredPlayerNum: PromiseOrValue<BigNumberish>,
      wagerAmount: PromiseOrValue<BigNumberish>,
      gameType: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    depositOrPlay(
      escrowHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  createGameAndDepositInitialWager(
    tokenAddress: PromiseOrValue<string>,
    requiredPlayerNum: PromiseOrValue<BigNumberish>,
    wagerAmount: PromiseOrValue<BigNumberish>,
    gameType: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  depositOrPlay(
    escrowHash: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createGameAndDepositInitialWager(
      tokenAddress: PromiseOrValue<string>,
      requiredPlayerNum: PromiseOrValue<BigNumberish>,
      wagerAmount: PromiseOrValue<BigNumberish>,
      gameType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    depositOrPlay(
      escrowHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    createGameAndDepositInitialWager(
      tokenAddress: PromiseOrValue<string>,
      requiredPlayerNum: PromiseOrValue<BigNumberish>,
      wagerAmount: PromiseOrValue<BigNumberish>,
      gameType: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    depositOrPlay(
      escrowHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createGameAndDepositInitialWager(
      tokenAddress: PromiseOrValue<string>,
      requiredPlayerNum: PromiseOrValue<BigNumberish>,
      wagerAmount: PromiseOrValue<BigNumberish>,
      gameType: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    depositOrPlay(
      escrowHash: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
