/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWegaChanceGame,
  IWegaChanceGameInterface,
} from "../../../contracts/games/IWegaChanceGame";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "randomNumbers",
        type: "uint256[]",
      },
    ],
    name: "addRandomNumbers",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "randomNumbersCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "denominator",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "player",
        type: "address",
      },
    ],
    name: "roll",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWegaChanceGame__factory {
  static readonly abi = _abi;
  static createInterface(): IWegaChanceGameInterface {
    return new utils.Interface(_abi) as IWegaChanceGameInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWegaChanceGame {
    return new Contract(address, _abi, signerOrProvider) as IWegaChanceGame;
  }
}
