/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWegaCoinFlipGame,
  IWegaCoinFlipGameInterface,
} from "../../../contracts/games/IWegaCoinFlipGame";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "escrowHash",
        type: "bytes32",
      },
      {
        internalType: "address[]",
        name: "currentPlayers",
        type: "address[]",
      },
      {
        internalType: "uint256[]",
        name: "playerChoises",
        type: "uint256[]",
      },
      {
        internalType: "uint256",
        name: "denominator",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minRounds",
        type: "uint256",
      },
    ],
    name: "play",
    outputs: [
      {
        internalType: "address[]",
        name: "winners",
        type: "address[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWegaCoinFlipGame__factory {
  static readonly abi = _abi;
  static createInterface(): IWegaCoinFlipGameInterface {
    return new utils.Interface(_abi) as IWegaCoinFlipGameInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWegaCoinFlipGame {
    return new Contract(address, _abi, signerOrProvider) as IWegaCoinFlipGame;
  }
}
