/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IWegaInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "play(bytes32,address[],uint256[],uint256,uint256)"
      | "play(bytes32,address[],uint256,uint256)"
      | "playerResults"
      | "playerScore"
      | "randomNumbersContract"
      | "winners"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "play(bytes32,address[],uint256[],uint256,uint256)",
    values: [
      BytesLike,
      AddressLike[],
      BigNumberish[],
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "play(bytes32,address[],uint256,uint256)",
    values: [BytesLike, AddressLike[], BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "playerResults",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "playerScore",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "randomNumbersContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "winners", values: [BytesLike]): string;

  decodeFunctionResult(
    functionFragment: "play(bytes32,address[],uint256[],uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "play(bytes32,address[],uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "randomNumbersContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "winners", data: BytesLike): Result;
}

export interface IWega extends BaseContract {
  connect(runner?: ContractRunner | null): IWega;
  waitForDeployment(): Promise<this>;

  interface: IWegaInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  "play(bytes32,address[],uint256[],uint256,uint256)": TypedContractMethod<
    [
      escrowHash: BytesLike,
      currentPlayers: AddressLike[],
      playerChoises: BigNumberish[],
      denominator: BigNumberish,
      minRounds: BigNumberish
    ],
    [string[]],
    "nonpayable"
  >;

  "play(bytes32,address[],uint256,uint256)": TypedContractMethod<
    [
      escrowHash: BytesLike,
      currentPlayers: AddressLike[],
      denominator: BigNumberish,
      minRounds: BigNumberish
    ],
    [string[]],
    "nonpayable"
  >;

  playerResults: TypedContractMethod<
    [escrowHash: BytesLike, player: AddressLike],
    [bigint[]],
    "view"
  >;

  playerScore: TypedContractMethod<
    [escrowHash: BytesLike, player: AddressLike],
    [bigint],
    "view"
  >;

  randomNumbersContract: TypedContractMethod<[], [string], "view">;

  winners: TypedContractMethod<[escrowHash: BytesLike], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "play(bytes32,address[],uint256[],uint256,uint256)"
  ): TypedContractMethod<
    [
      escrowHash: BytesLike,
      currentPlayers: AddressLike[],
      playerChoises: BigNumberish[],
      denominator: BigNumberish,
      minRounds: BigNumberish
    ],
    [string[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "play(bytes32,address[],uint256,uint256)"
  ): TypedContractMethod<
    [
      escrowHash: BytesLike,
      currentPlayers: AddressLike[],
      denominator: BigNumberish,
      minRounds: BigNumberish
    ],
    [string[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "playerResults"
  ): TypedContractMethod<
    [escrowHash: BytesLike, player: AddressLike],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "playerScore"
  ): TypedContractMethod<
    [escrowHash: BytesLike, player: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "randomNumbersContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "winners"
  ): TypedContractMethod<[escrowHash: BytesLike], [string[]], "view">;

  filters: {};
}
